# Generated by Django 6.0.3 on 2026-03-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (RU)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Tuman nomi (UZ)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Tuman nomi (RU)')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Viloyat nomi (UZ)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Viloyat nomi (RU)')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('price', models.PositiveBigIntegerField(verbose_name='Narx')),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name="To'liq tavsif")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil (ixtiyoriy)')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='Google Maps link (ixtiyoriy)')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('is_active_business', models.BooleanField(default=True, verbose_name='Faol biznesmi?')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('inactive', 'Faol emas'), ('delete_requested', 'O‘chirish so‘ralgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.category', verbose_name='Kategoriya')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.district', verbose_name='Tuman / shahar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name="E'lon egasi")),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.region', verbose_name='Viloyat')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='listings.region', verbose_name='Viloyat'),
        ),
    ]
