# Generated by Django 6.0.3 on 2026-03-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_category_slug_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/main_images/', verbose_name='Asosiy rasm'),
        ),
    ]
