# Generated by Django 6.0.3 on 2026-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delete_request_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'chirish so'rovi vaqti"),
        ),
    ]
