# Generated by Django 6.0.3 on 2026-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_delete_request_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='delete_request_at',
        ),
        migrations.AddField(
            model_name='listing',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='O‘chirish so‘rovi vaqti'),
        ),
    ]
