# Generated by Django 6.0.3 on 2026-03-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
