# Generated by Django 6.0.3 on 2026-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
