# Generated by Django 6.0.3 on 2026-04-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Featured e'lonmi?"),
        ),
    ]
